import Foundation
@testable import Macterm
import Testing

@MainActor
struct WorkspaceSerializerTests {
    // Round-trip: snapshot -> restore -> compare topology.
    private func roundTrip(_ workspaces: [UUID: Workspace]) -> [Workspace] {
        let snaps = WorkspaceSerializer.snapshot(workspaces)
        let valid = Set(workspaces.keys)
        return WorkspaceSerializer.restore(from: snaps, validIDs: valid)
    }

    @Test
    func round_trip_single_tab_single_pane_preserves_paths() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp/a")
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped.count == 1)
        #expect(roundTripped[0].tabs.count == 1)
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            #expect(p.projectPath == "/tmp/a")
        } else {
            Issue.record("expected leaf")
        }
    }

    @Test
    func round_trip_preserves_tab_and_workspace_ids() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let tabID = ws.tabs[0].id
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped[0].projectID == ws.projectID)
        #expect(roundTripped[0].tabs[0].id == tabID)
    }

    @Test
    func round_trip_preserves_nested_topology() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let (tree, ids) = build(H(pane("a"), V(pane("b"), pane("c"), ratio: 0.3), ratio: 0.4))
        ws.tabs[0].splitRoot = tree

        let roundTripped = roundTrip([ws.projectID: ws])
        let restoredRoot = roundTripped[0].tabs[0].splitRoot

        // Pane IDs are regenerated by restoreNode — check structure via
        // rendering with a new name map keyed on path, which we can
        // reconstruct because each pane's projectPath is unique to /.
        #expect(restoredRoot.allPanes().count == 3)
        // Topology: outer horizontal (0.4), inner vertical (0.3).
        guard case let .split(outer) = restoredRoot, outer.direction == .horizontal else {
            Issue.record("expected outer horizontal split")
            return
        }
        #expect(abs(outer.ratio - 0.4) < 0.0001)
        guard case let .split(inner) = outer.second, inner.direction == .vertical else {
            Issue.record("expected inner vertical split")
            return
        }
        #expect(abs(inner.ratio - 0.3) < 0.0001)
        _ = ids
    }

    @Test
    func round_trip_preserves_custom_title() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        ws.tabs[0].customTitle = "My Custom Title"
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped[0].tabs[0].customTitle == "My Custom Title")
    }

    @Test
    func round_trip_preserves_active_tab_when_valid() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let second = ws.createTab(projectPath: "/tmp")
        ws.selectTab(second.id)
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped[0].activeTabID == second.id)
    }

    @Test
    func round_trip_falls_back_to_first_tab_when_active_missing() {
        // Simulate a corrupt snapshot where activeTabID doesn't match any tab.
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws])
        var snap = snaps[0]
        snap = WorkspaceSnapshot(projectID: snap.projectID, activeTabID: UUID(), tabs: snap.tabs)
        let restored = WorkspaceSerializer.restore(from: [snap], validIDs: [ws.projectID])
        #expect(restored.count == 1)
        // Workspace.init treats an unknown activeTabID as if nil and picks the first tab.
        #expect(restored[0].activeTabID == restored[0].tabs.first?.id)
    }

    @Test
    func restore_skips_workspaces_for_removed_projects() {
        let kept = Workspace(projectID: UUID(), projectPath: "/tmp/a")
        let dropped = Workspace(projectID: UUID(), projectPath: "/tmp/b")
        let snaps = WorkspaceSerializer.snapshot([kept.projectID: kept, dropped.projectID: dropped])
        let restored = WorkspaceSerializer.restore(from: snaps, validIDs: [kept.projectID])
        #expect(restored.count == 1)
        #expect(restored[0].projectID == kept.projectID)
    }

    @Test
    func restore_skips_workspaces_with_no_tabs() {
        // Build a hand-rolled empty-tabs snapshot.
        let pid = UUID()
        let snap = WorkspaceSnapshot(projectID: pid, activeTabID: nil, tabs: [])
        let restored = WorkspaceSerializer.restore(from: [snap], validIDs: [pid])
        #expect(restored.isEmpty)
    }

    @Test
    func snapshot_preserves_focused_pane_id() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let tab = ws.tabs[0]
        let (tree, ids) = build(H(pane("a"), pane("b")))
        tab.splitRoot = tree
        tab.focusedPaneID = ids["b"]
        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws])
        #expect(snaps[0].tabs[0].focusedPaneID == ids["b"])
    }

    @Test
    func round_trip_preserves_done_attention_state() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        if case let .pane(p) = ws.tabs[0].splitRoot {
            p.recordUserInteraction()
            p.markCommandRunning()
            p.markCommandFinished()
            #expect(p.executionState == .done)
        }
        let roundTripped = roundTrip([ws.projectID: ws])
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            #expect(p.executionState == .done)
        } else {
            Issue.record("expected leaf")
        }
    }

    @Test
    func round_trip_does_not_persist_idle_or_running() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        if case let .pane(p) = ws.tabs[0].splitRoot {
            // Idle stays idle.
            #expect(p.executionState == .idle)
        }
        let idleRound = roundTrip([ws.projectID: ws])
        if case let .pane(p) = idleRound[0].tabs[0].splitRoot {
            #expect(p.executionState == .idle)
        }
    }

    @Test
    func restore_done_is_cleared_by_acknowledge() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        if case let .pane(p) = ws.tabs[0].splitRoot {
            p.recordUserInteraction()
            p.markCommandRunning()
            p.markCommandFinished()
        }
        let roundTripped = roundTrip([ws.projectID: ws])
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            #expect(p.executionState == .done)
            p.acknowledgeCommandCompletion()
            #expect(p.executionState == .idle)
        } else {
            Issue.record("expected leaf")
        }
    }

    @Test
    func roundtrip_via_WorkspaceStore_on_disk() {
        // End-to-end: encode, write to a temp file, load back, restore.
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp)

        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let (tree, _) = build(H(pane("a"), pane("b")))
        ws.tabs[0].splitRoot = tree

        store.save(WorkspaceSerializer.snapshot([ws.projectID: ws]))
        let reloaded = store.load()
        #expect(reloaded.count == 1)
        #expect(reloaded[0].projectID == ws.projectID)

        let restored = WorkspaceSerializer.restore(from: reloaded, validIDs: [ws.projectID])
        #expect(restored[0].tabs[0].splitRoot.allPanes().count == 2)
    }

    @Test
    func load_v3_file_clears_persisted_attention_bits() throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-v3-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp)
        let projectID = UUID()
        let tabID = UUID()
        let paneID = UUID()
        let file = WorkspacesFile(
            version: 3,
            workspaces: [WorkspaceSnapshot(
                projectID: projectID,
                activeTabID: tabID,
                tabs: [TabSnapshot(
                    id: tabID,
                    customTitle: nil,
                    focusedPaneID: paneID,
                    splitRoot: .pane(PaneSnapshot(
                        id: paneID,
                        projectPath: "/tmp",
                        needsAttention: true
                    ))
                )]
            )]
        )
        let encoder = JSONEncoder()
        try encoder.encode(file).write(to: tmp)

        let restored = WorkspaceSerializer.restore(from: store.load(), validIDs: [projectID])

        #expect(restored.first?.tabs.first?.executionState == .idle)
    }

    @Test
    func load_from_missing_file_returns_empty() {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-doesnotexist-\(UUID().uuidString).json")
        let store = WorkspaceStore(fileURL: tmp)
        #expect(store.load().isEmpty)
    }

    @Test
    func load_from_malformed_file_returns_empty() throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-malformed-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        try Data("not valid json {".utf8).write(to: tmp)
        let store = WorkspaceStore(fileURL: tmp)
        #expect(store.load().isEmpty)
    }

    // MARK: - Remote-pane persistence (data-loss regression, #4.1)

    @Test
    func snapshot_persists_remote_spec_verbatim_with_nil_working_directory() {
        // A remote pane's projectPath is an scp-style spec. It MUST be
        // persisted verbatim (so restore parses it as .remote and reattaches
        // over ssh), and workingDirectory MUST be nil — a remote pane's live
        // cwd is a remote-filesystem path with no host prefix that would parse
        // as a bogus LOCAL dir and orphan the remote session.
        let spec = "devbox:~/dev/api"
        let ws = Workspace(projectID: UUID(), projectPath: spec)
        #expect(ws.tabs[0].splitRoot.allPanes().first?.isRemote == true)

        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws])
        guard case let .pane(p) = snaps[0].tabs[0].splitRoot else {
            Issue.record("expected leaf")
            return
        }
        #expect(p.projectPath == spec)
        #expect(p.workingDirectory == nil)
    }

    @Test
    func remote_pane_round_trips_as_remote() {
        // End-to-end: a restored remote pane must still be remote (drives the
        // ssh/zmx spawn path), not silently downgraded to a local shell.
        let spec = "user@host:/srv/app"
        let ws = Workspace(projectID: UUID(), projectPath: spec)
        let restored = roundTrip([ws.projectID: ws])
        let pane = restored.first?.tabs.first?.splitRoot.allPanes().first
        #expect(pane?.isRemote == true)
        #expect(pane?.projectPath == spec)
    }

    // MARK: - Corrupt-file save refusal (data-loss regression, #4.4)

    @Test
    func save_refuses_after_corrupt_load_so_autosave_cannot_clobber() throws {
        // A present-but-undecodable file must NOT be overwritten by the next
        // autosave — that would permanently destroy the user's persisted tabs.
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-corrupt-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let garbage = Data("{ corrupt not json".utf8)
        try garbage.write(to: tmp)

        let store = WorkspaceStore(fileURL: tmp)
        #expect(store.load().isEmpty) // present-but-undecodable → empty + latch

        // The next mutation's autosave must be refused, leaving the file intact.
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        store.save(WorkspaceSerializer.snapshot([ws.projectID: ws]))

        #expect(try Data(contentsOf: tmp) == garbage)
    }

    @Test
    func save_proceeds_after_clean_load() {
        // The refusal must be scoped to a FAILED load — a store that loaded
        // cleanly (or from absent) still saves normally.
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-clean-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp) // absent file → clean load
        _ = store.load()

        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        store.save(WorkspaceSerializer.snapshot([ws.projectID: ws]))

        #expect(FileManager.default.fileExists(atPath: tmp.path))
        #expect(WorkspaceStore(fileURL: tmp).load().count == 1)
    }
}

@MainActor
struct WorkspaceSerializerSessionIdentityTests {
    @Test
    func round_trips_session_identity_and_working_directory() throws {
        let projectID = UUID()
        let pane = Pane(projectPath: "/tmp/proj", projectID: projectID)
        let tab = TerminalTab(id: UUID(), splitRoot: .pane(pane), focusedPaneID: pane.id)
        let ws = Workspace(projectID: projectID, tabs: [tab], activeTabID: tab.id)

        let snapshots = WorkspaceSerializer.snapshot([projectID: ws])
        let restored = try #require(
            WorkspaceSerializer.restore(from: snapshots, validIDs: [projectID]).first
        )
        let restoredPane = try #require(restored.tabs.first?.splitRoot.allPanes().first)

        // Session identity survives verbatim; the runtime pane id does not.
        #expect(restoredPane.sessionID == pane.sessionID)
        #expect(restoredPane.sessionName == pane.sessionName)
        #expect(restoredPane.id != pane.id)
        // With no live surface the cwd falls back to the project path.
        #expect(restoredPane.projectPath == "/tmp/proj")
    }

    @Test
    func old_snapshot_without_identity_gets_a_fresh_session() throws {
        let projectID = UUID()
        let snap = WorkspaceSnapshot(
            projectID: projectID,
            activeTabID: nil,
            tabs: [TabSnapshot(
                id: UUID(),
                customTitle: nil,
                focusedPaneID: nil,
                splitRoot: .pane(PaneSnapshot(id: UUID(), projectPath: "/tmp/old"))
            )]
        )
        let restored = try #require(
            WorkspaceSerializer.restore(from: [snap], validIDs: [projectID]).first
        )
        let pane = try #require(restored.tabs.first?.splitRoot.allPanes().first)
        #expect(pane.sessionName.hasPrefix(ZmxSessionName.prefix))
        #expect(pane.projectPath == "/tmp/old")
    }

    @Test
    func restored_pane_uses_persisted_name_over_rederivation() throws {
        // The persisted name's slug reflects the project AT CREATION — a
        // rename must not re-derive it, or reattach targets a dead session.
        let projectID = UUID()
        let sessionID = UUID()
        let snap = WorkspaceSnapshot(
            projectID: projectID,
            activeTabID: nil,
            tabs: [TabSnapshot(
                id: UUID(),
                customTitle: nil,
                focusedPaneID: nil,
                splitRoot: .pane(PaneSnapshot(
                    id: UUID(),
                    projectPath: "/tmp/renamed-project",
                    sessionID: sessionID,
                    sessionName: "macterm-oldname-aaaaaaaabbbb",
                    workingDirectory: "/tmp/renamed-project/src"
                ))
            )]
        )
        let restored = try #require(
            WorkspaceSerializer.restore(from: [snap], validIDs: [projectID]).first
        )
        let pane = try #require(restored.tabs.first?.splitRoot.allPanes().first)
        #expect(pane.sessionName == "macterm-oldname-aaaaaaaabbbb")
        #expect(pane.sessionID == sessionID)
        #expect(pane.sessionSlug == "oldname")
        #expect(pane.projectPath == "/tmp/renamed-project/src")
    }
}
