@testable import Macterm
import XCTest

@MainActor
final class WorkspaceSerializerTests: XCTestCase {
    // Round-trip: snapshot -> restore -> compare topology.
    private func roundTrip(_ workspaces: [UUID: Workspace]) -> [Workspace] {
        let snaps = WorkspaceSerializer.snapshot(workspaces)
        let valid = Set(workspaces.keys)
        return WorkspaceSerializer.restore(from: snaps, validIDs: valid)
    }

    func test_round_trip_single_tab_single_pane_preserves_paths() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp/a")
        let roundTripped = roundTrip([ws.projectID: ws])
        XCTAssertEqual(roundTripped.count, 1)
        XCTAssertEqual(roundTripped[0].tabs.count, 1)
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            XCTAssertEqual(p.projectPath, "/tmp/a")
        } else {
            XCTFail("expected leaf")
        }
    }

    func test_round_trip_preserves_tab_and_workspace_ids() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let tabID = ws.tabs[0].id
        let roundTripped = roundTrip([ws.projectID: ws])
        XCTAssertEqual(roundTripped[0].projectID, ws.projectID)
        XCTAssertEqual(roundTripped[0].tabs[0].id, tabID)
    }

    func test_round_trip_preserves_nested_topology() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let (tree, ids) = build(H(pane("a"), V(pane("b"), pane("c"), ratio: 0.3), ratio: 0.4))
        ws.tabs[0].splitRoot = tree

        let roundTripped = roundTrip([ws.projectID: ws])
        let restoredRoot = roundTripped[0].tabs[0].splitRoot

        // Pane IDs are regenerated by restoreNode — check structure via
        // rendering with a new name map keyed on path, which we can
        // reconstruct because each pane's projectPath is unique to /.
        XCTAssertEqual(restoredRoot.allPanes().count, 3)
        // Topology: outer horizontal (0.4), inner vertical (0.3).
        guard case let .split(outer) = restoredRoot, outer.direction == .horizontal else {
            return XCTFail("expected outer horizontal split")
        }
        XCTAssertEqual(outer.ratio, 0.4, accuracy: 0.0001)
        guard case let .split(inner) = outer.second, inner.direction == .vertical else {
            return XCTFail("expected inner vertical split")
        }
        XCTAssertEqual(inner.ratio, 0.3, accuracy: 0.0001)
        _ = ids
    }

    func test_round_trip_preserves_custom_title() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        ws.tabs[0].customTitle = "My Custom Title"
        let roundTripped = roundTrip([ws.projectID: ws])
        XCTAssertEqual(roundTripped[0].tabs[0].customTitle, "My Custom Title")
    }

    func test_round_trip_preserves_active_tab_when_valid() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let second = ws.createTab(projectPath: "/tmp")
        ws.selectTab(second.id)
        let roundTripped = roundTrip([ws.projectID: ws])
        XCTAssertEqual(roundTripped[0].activeTabID, second.id)
    }

    func test_round_trip_falls_back_to_first_tab_when_active_missing() {
        // Simulate a corrupt snapshot where activeTabID doesn't match any tab.
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws])
        var snap = snaps[0]
        snap = WorkspaceSnapshot(projectID: snap.projectID, activeTabID: UUID(), tabs: snap.tabs)
        let restored = WorkspaceSerializer.restore(from: [snap], validIDs: [ws.projectID])
        XCTAssertEqual(restored.count, 1)
        // Workspace.init treats an unknown activeTabID as if nil and picks the first tab.
        XCTAssertEqual(restored[0].activeTabID, restored[0].tabs.first?.id)
    }

    func test_restore_skips_workspaces_for_removed_projects() {
        let kept = Workspace(projectID: UUID(), projectPath: "/tmp/a")
        let dropped = Workspace(projectID: UUID(), projectPath: "/tmp/b")
        let snaps = WorkspaceSerializer.snapshot([kept.projectID: kept, dropped.projectID: dropped])
        let restored = WorkspaceSerializer.restore(from: snaps, validIDs: [kept.projectID])
        XCTAssertEqual(restored.count, 1)
        XCTAssertEqual(restored[0].projectID, kept.projectID)
    }

    func test_restore_skips_workspaces_with_no_tabs() {
        // Build a hand-rolled empty-tabs snapshot.
        let pid = UUID()
        let snap = WorkspaceSnapshot(projectID: pid, activeTabID: nil, tabs: [])
        let restored = WorkspaceSerializer.restore(from: [snap], validIDs: [pid])
        XCTAssertTrue(restored.isEmpty)
    }

    func test_snapshot_preserves_focused_pane_id() throws {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let tab = ws.tabs[0]
        let (tree, ids) = build(H(pane("a"), pane("b")))
        tab.splitRoot = tree
        tab.focusedPaneID = try XCTUnwrap(ids["b"])
        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws])
        XCTAssertEqual(snaps[0].tabs[0].focusedPaneID, ids["b"])
    }

    func test_roundtrip_via_WorkspaceStore_on_disk() {
        // End-to-end: encode, write to a temp file, load back, restore.
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp)

        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let (tree, _) = build(H(pane("a"), pane("b")))
        ws.tabs[0].splitRoot = tree

        store.save(WorkspaceSerializer.snapshot([ws.projectID: ws]))
        let reloaded = store.load()
        XCTAssertEqual(reloaded.count, 1)
        XCTAssertEqual(reloaded[0].projectID, ws.projectID)

        let restored = WorkspaceSerializer.restore(from: reloaded, validIDs: [ws.projectID])
        XCTAssertEqual(restored[0].tabs[0].splitRoot.allPanes().count, 2)
    }

    func test_load_from_missing_file_returns_empty() {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-doesnotexist-\(UUID().uuidString).json")
        let store = WorkspaceStore(fileURL: tmp)
        XCTAssertTrue(store.load().isEmpty)
    }

    func test_load_from_malformed_file_returns_empty() throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-malformed-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        try Data("not valid json {".utf8).write(to: tmp)
        let store = WorkspaceStore(fileURL: tmp)
        XCTAssertTrue(store.load().isEmpty)
    }
}
