name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Checks
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Setup GhosttyKit
        run: mise run setup
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Check
        run: mise run check
